CarSiteSecond/CarSiteSecond/Models/DTOs/PurchaseType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarSiteSecond.Models.DTOs
{
    public class PurchaseType
    {
        public PurchaseType(int id, string type)
        {
            this.id = id;
            Type = type;
        }

        public PurchaseType()
        {
            this.id = 0;
            Type = "";
        }

        public int id { get; set; }
        public string Type { get; set; }
    }
}

CarSiteSecond/CarSiteSecond/Models/DTOs/Sale.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarSiteSecond.Models.DTOs
{
    public class Sale
    {
        public Sale(int id, int purchaseType, string name, string email, string street1, string street2, string city, string state, string zip, string phone, int carID, string userID, decimal purchasePrice, string date)
        {
            this.id = id;
            PurchaseType = purchaseType;
            Name = name;
            Email = email;
            Street1 = street1;
            Street2 = street2;
            City = city;
            State = state;
            Zip = zip;
            Phone = phone;
            CarID = carID;
            UserID = userID;
            PurchasePrice = purchasePrice;
            Date = date;
        }

        public Sale()
        {
            this.id = 0;
            PurchaseType = 0;
            Name = "";
            Email = "";
            Street1 = "";
            Street2 = "";
            City = "";
            State = "";
            Zip = "";
            Phone = "";
            CarID = 0;
            UserID = "";
            PurchasePrice = 0m;
            Date = DateTime.Today.ToShortDateString();
        }

        public int id { get; set; }
        public int PurchaseType { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public int CarID { get; set; }
        public string UserID { get; set; }
        public decimal PurchasePrice { get; set; }
        public string Date { get; set; }
    }
}

CarSiteSecond/CarSiteSecond/ViewModels/PurchaseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarSiteSecond.ViewModels
{
    public class PurchaseViewModel
    {
        public PurchaseViewModel(int carId, int year, string bodyStyle, string trans, string color, string interior, int mileage, string vIN, decimal salePrice, decimal mSRP, string description, string pictureSrc, string make, string model, string email, string street1, string street2, string city, string state, string zip, string phone, string cusName, string saleName, decimal purchasePrice, List<string> purchaseTypes)
        {
            this.carId = carId;
            Year = year;
            BodyStyle = bodyStyle;
            Trans = trans;
            Color = color;
            Interior = interior;
            Mileage = mileage;
            VIN = vIN;
            SalePrice = salePrice;
            MSRP = mSRP;
            Description = description;
            PictureSrc = pictureSrc;
            Make = make;
            Model = model;
            Email = email;
            Street1 = street1;
            Street2 = street2;
            City = city;
            State = state;
            Zip = zip;
            Phone = phone;
            CusName = cusName;
            SaleId = saleName;
            PurchasePrice = purchasePrice;
            PurchaseTypes = purchaseTypes;
        }

        public PurchaseViewModel()
        {
            this.carId = 0;
            Year = 0;
            BodyStyle = "";
            Trans = "";
            Color = "";
            Interior = "";
            Mileage = 0;
            VIN = "";
            SalePrice = 0m;
            MSRP = 0m;
            Description = "";
            PictureSrc = "";
            Make = "";
            Model = "";
            Email = "";
            Street1 = "";
            Street2 = "";
            City = "";
            State = "";
            Zip = "";
            Phone = "";
            CusName = "";
            SaleId = "";
            PurchasePrice = 0m;
            PurchaseTypes = new List<string>();
        }

        public int carId { get; set; }
        public int Year { get; set; }
        public string BodyStyle { get; set; }
        public string Trans { get; set; }
        public string Color { get; set; }
        public string Interior { get; set; }
        [DisplayFormat(DataFormatString = "{0:n}", ApplyFormatInEditMode = true)]
        public int Mileage { get; set; }
        public string VIN { get; set; }
        [DisplayFormat(DataFormatString = "{0:c}", ApplyFormatInEditMode = true)]
        public decimal SalePrice { get; set; }
        [DisplayFormat(DataFormatString = "{0:c}", ApplyFormatInEditMode = true)]
        public decimal MSRP { get; set; }
        public string Description { get; set; }
        public string PictureSrc { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Email { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string CusName { get; set; }
        public string SaleId { get; set; }
        public decimal PurchasePrice { get; set; }
        public List<string> PurchaseTypes { get; set; }

    }
}

CarSiteSecond/CarSiteSecond/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarSiteSecond.Models.DTOs;
using CarSiteSecond.Models;
using CarSiteSecond.Models.Interfaces;
using CarSiteSecond.Models.Identity;
using CarSiteSecond.Models.Requests;
using CarSiteSecond.Models.Responses;
using CarSiteSecond.Data.Repos;
using CarSiteSecond.Data;
using CarSiteSecond.ViewModels;

namespace CarSiteSecond.Controllers
{
    public class SalesController : Controller
    {
        // GET: Sales

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]

        public ActionResult Purchase(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                IRepo repo = Factory.Create();
                CarRequest carRequest = new CarRequest();
                Car car = new Car();
                car.id = (int)id;
                carRequest.Cars.Add(car);
                CarResponse carResponse = new CarResponse();
                carResponse.Cars.Add(repo.GetCarsOne(carRequest).Cars.FirstOrDefault());
                if (carResponse.Cars.FirstOrDefault() == null || carResponse.Cars.FirstOrDefault().id == 0)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    PurchaseViewModel sale = new PurchaseViewModel();
                    MakeResponse makeResponse = repo.GetMakesAll(new MakeRequest());
                    ModelResponse modelResponse = repo.GetModelsAll(new ModelRequest());
                    InteriorResponse interiorResponse = repo.GetInteriorsAll(new InteriorRequest());
                    ColorResponse colorResponse = repo.GetColorsAll(new ColorRequest());
                    sale.carId = carResponse.Cars.FirstOrDefault().id;
                    sale.Interior = interiorResponse.Interiors.FirstOrDefault(i => i.id == carResponse.Cars.FirstOrDefault().InteriorID).InteriorName;
                    //Gets the MakeID by checking the ModelID of the car against the Models table, then gets the Make according to the MakeID, and outputs the MakeName
                    sale.Make = makeResponse.Makes.FirstOrDefault(y => y.id == modelResponse.Models.FirstOrDefault(x => x.id == carResponse.Cars.FirstOrDefault().ModelID).MakeID).MakeName;
                    sale.Model = modelResponse.Models.FirstOrDefault(x => x.id == carResponse.Cars.FirstOrDefault().ModelID).ModelName;
                    sale.Mileage = carResponse.Cars.FirstOrDefault().Mileage;
                    sale.MSRP = carResponse.Cars.FirstOrDefault().MSRP;
                    sale.PictureSrc = carResponse.Cars.FirstOrDefault().PictureSrc;
                    sale.SalePrice = carResponse.Cars.FirstOrDefault().SalePrice;
                    sale.Trans = carResponse.Cars.FirstOrDefault().Transmission;
                    sale.VIN = carResponse.Cars.FirstOrDefault().VIN;
                    sale.Year = carResponse.Cars.FirstOrDefault().Year;
                    sale.BodyStyle = carResponse.Cars.FirstOrDefault().BodyStyle;
                    sale.Color = colorResponse.Colors.FirstOrDefault(c => c.id == carResponse.Cars.FirstOrDefault().ColorID).ColorName;
                    sale.Description = carResponse.Cars.FirstOrDefault().Description;
                    PurchaseTypeRequest purchaseTypeRequest = new PurchaseTypeRequest();
                    PurchaseTypeResponse purchaseTypeResponse = repo.GetPurchaseTypesAll(purchaseTypeRequest);
                    foreach (PurchaseType p in purchaseTypeResponse.PurchaseTypes)
                    {
                        sale.PurchaseTypes.Add(p.Type);
                    }
                    return View(sale);
                }
            }
        }

        [HttpPost]

        public ActionResult PurchaseSave(PurchaseViewModel sale)
        {
            if (sale.SaleId != "")
            {
                IRepo repo = Factory.Create();
                SaleRequest saleRequest = new SaleRequest();
                Sale sales = new Sale();
                sales.CarID = sale.carId;
                sales.City = sale.City;
                sales.Email = sale.Email;
                sales.Name = sale.CusName;
                sales.Phone = sale.Phone;
                sales.PurchasePrice = sale.PurchasePrice;
                PurchaseTypeRequest purchaseTypeRequest = new PurchaseTypeRequest();
                PurchaseTypeResponse purchaseTypeResponse = repo.GetPurchaseTypesAll(purchaseTypeRequest);
                sales.PurchaseType = purchaseTypeResponse.PurchaseTypes.FirstOrDefault().id;
                sales.State = sale.State;
                sales.Street1 = sale.Street1;
                sales.Street2 = sale.Street2;
                UserRequest userRequest = new UserRequest();
                UserResponse userResponse = new UserResponse();
                userResponse = repo.GetUsersAll(userRequest);
                sales.UserID = userResponse.Users.FirstOrDefault(x => x.UserName == sale.SaleId).Id;
                sales.Zip = sale.Zip;
                saleRequest.Sales.Add(sales);
                repo.CreateSalesOne(saleRequest);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

CarSiteSecond/CarSiteSecond/Views/Sales/Purchase.cshtml
@model CarSiteSecond.ViewModels.PurchaseViewModel
@{
    ViewBag.Title = "Purchase";
}

<h1>Purchase Vehicle</h1>
@using (Html.BeginForm("PurchaseSave", "Sales", Model))
{

    <div id="details-container">
        <div class="border-mine" style="padding:5px;">
            <table id="purchase-results-table" class="results-table" style="padding:15px;">
                <tr>
                    <td class="bold left-text">@Model.Year @Model.Make @Model.Model</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td rowspan="3"><img src="@Url.Content(Model.PictureSrc)" /></td>
                    <td class="bold right-text">Body Style:</td>
                    <td class="left-text">@Model.BodyStyle</td>
                    <td class="bold right-text">Interior:</td>
                    <td class="left-text">@Model.Interior</td>
                    <td class="bold right-text">Sale Price:</td>
                    <td class="left-text">@Model.SalePrice.ToString("C")</td>
                </tr>
                <tr>
                    <td class="bold right-text">Trans:</td>
                    <td class="left-text">@Model.Trans</td>
                    <td class="bold right-text">Mileage:</td>
                    <td class="left-text">@Model.Mileage</td>
                    <td class="bold right-text">MSRP:</td>
                    <td class="left-text">@Model.MSRP.ToString("C")</td>
                </tr>
                <tr>
                    <td class="bold right-text">Color:</td>
                    <td class="left-text">@Model.Color</td>
                    <td class="bold right-text">Vin #:</td>
                    <td class="left-text">@Model.VIN</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td class="right-text bold">Description:</td>
                    <td colspan="5" class="left-text">@Model.Description</td>
                </tr>
            </table>
        </div>
    </div>

    <h1>Sales Information</h1>
    <div class="form-group">
        <table>
            <tr>
                <td class="left-text bold">Name</td>
                <td class="left-text bold">Phone</td>
                <td class="left-text bold"><input id="SaleId" name="SaleId" value="@User.Identity.Name" hidden readonly></td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="CusName" value="" name="CusName" />
                </td>
                <td>
                    <input type="text" id="Phone" value="" name="Phone"/>
                </td>
            </tr>
            <tr>
                <td class="left-text bold">Email</td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="Email" value="" name="Email" />
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="left-text bold">Street 1</td>
                <td class="left-text bold">Street 2</td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="Street1" value="" name="Street1" />
                </td>
                <td>
                    <input type="text" id="Street2" value="" name="Street2" />
                </td>
            </tr>
            <tr>
                <td class="left-text bold">City</td>
                <td class="left-text bold">State</td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="City" value="" name="City"/>
                </td>
                <td>
                    <select id="State" name="State">
                        <option value="Alabama">AL</option>
                        <option value="Alaska">AK</option>
                        <option value="Arizona">AZ</option>
                        <option value="Arkansas">AR</option>
                        <option value="California">CA</option>
                        <option value="Colorado">CO</option>
                        <option value="Connecticut">CT</option>
                        <option value="Delaware">DE</option>
                        <option value="Florida">FL</option>
                        <option value="Georgia">GA</option>
                        <option value="Hawaii">HI</option>
                        <option value="Idaho">ID</option>
                        <option value="Illinois">IL</option>
                        <option value="Indiana">IN</option>
                        <option value="Iowa">IA</option>
                        <option value="Kansas">KS</option>
                        <option value="Kentucky">KY</option>
                        <option value="Louisiana">LA</option>
                        <option value="Maine">ME</option>
                        <option value="Maryland">MD</option>
                        <option value="Massachusetts">MA</option>
                        <option value="Michigan">MI</option>
                        <option value="Minnesota">MN</option>
                        <option value="Mississippi">MS</option>
                        <option value="Missouri">MO</option>
                        <option value="Montana">MT</option>
                        <option value="Nebraska">NE</option>
                        <option value="Nevada">NV</option>
                        <option value="New Hampshire">NH</option>
                        <option value="New Jersey">NJ</option>
                        <option value="New Mexico">NM</option>
                        <option value="New York">NY</option>
                        <option value="North Carolina">NC</option>
                        <option value="North Dakota">ND</option>
                        <option value="Ohio">OH</option>
                        <option value="Oklahoma">OK</option>
                        <option value="Oregon">OR</option>
                        <option value="Pennsylvania">PA</option>
                        <option value="Rhode Island">RI</option>
                        <option value="South Carolina">SC</option>
                        <option value="South Dakota">SD</option>
                        <option value="Tennessee">TN</option>
                        <option value="Texas">TX</option>
                        <option value="Utah">UT</option>
                        <option value="Vermont">VT</option>
                        <option value="Virginia">VA</option>
                        <option value="Washington">WA</option>
                        <option value="West Virginia">WV</option>
                        <option value="Wisconsin">WI</option>
                        <option value="Wyoming">WY</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="left-text bold">Zipcode</td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="Zip" name="Zip" value="" />
                </td>
            </tr>
            <tr class="border-bottom"></tr>
            <tr>
                <td class="left-text bold">Purchase Price</td>
                <td class="left-text bold">Purchase Type</td>
            </tr>
            <tr>
                <td>
                    <input type="number" id="PurchasePrice" value="" name="PurchasePrice" />
                </td>
                <td>
                    @Html.DropDownListFor(p => p.PurchaseTypes,
                    new SelectList(Model.PurchaseTypes, "PurchaseTypes"))
                </td>
            </tr>
        </table>
    </div>
    <button type="submit">Save</button>
}



@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label>State</label>
            @Html.TextBoxFor(m => m.StateName, new { @class = "form-control", placeholder = "State Name" })
            @Html.TextBoxFor(m => m.StateAbbreviation, new { @class = "form-control", placeholder = "State Abbreviation" })
        </div>
        <button type="submit" class="btn btn-sm btn-primary">Save</button>
    }*@